name: portfolio_frontend

services:
    frontend:
        container_name: portfolio_frontend
        build: .
        image: miguelbritobarbosa/portfolio_frontend:latest
        restart: always
        env_file: .env
        environment:
            NEXT_PUBLIC_SITE_NAME: ${NEXT_PUBLIC_SITE_NAME}
            NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
            NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
            NODE_ENV: ${NODE_ENV}
        volumes:
            - ./src:/portfolio/src
            - ./package.json:/portfolio/package.json
            - ./package-lock.json:/portfolio/package-lock.json
            - ./.env:/portfolio/.env
            - ./public:/portfolio/public/
        ports:
            - "3000:3000"
