name: portifolio_backend

services:
    database:
        container_name: "portfolio_database"
        image: mysql:latest
        restart: always
        environment:
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        volumes:
            - portfolio_database:/var/lib/mysql
        networks:
            - strapi

    strapi:
        container_name: portifolio_backend
        build: .
        restart: always
        env_file: .env
        environment:
            DATABASE_CLIENT: ${DATABASE_CLIENT}
            DATABASE_HOST: database
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            JWT_SECRET: ${JWT_SECRET}
            ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
            APP_KEYS: ${APP_KEYS}
            NODE_ENV: ${NODE_ENV}
        volumes:
            - ./config:/portfolio/backend/config
            - ./src:/portfolio/backend/src
            - ./package.json:/portfolio/package.json
            - ./package-lock.json:/portfolio/package-lock.json
            - ./.env:/portfolio/backend/.env
            - ./public/uploads:/portfolio/backend/public/uploads
        ports:
            - "1337:1337"
        networks:
            - strapi
        depends_on:
            - database

   

volumes:
    portfolio_database:
        

networks:
  strapi:
    name: Strapi
    driver: bridge