version: "3.8"

services:
    database:
        container_name: "portfolio_database"
        image: mysql:latest
        restart: always
        environment:
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        volumes:
            - portfolio_database:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    portfolio_database:
        driver: local
